language: php

php:
  - 7.2
  - 7.3

sudo: false

install:
  - travis_retry composer install --no-interaction

script:
  - php $OPTIONS vendor/bin/phpunit --coverage-clover clover.xml

after_script:
  - bash <(curl -s https://codecov.io/bash)
