name: CI

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [7.2, 7.3, 7.4, 8.0]
        extension: [":bcmath", ":gmp"]

    name: PHP ${{ matrix.php }}

    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
          extensions: ${{ matrix.extension }}
          tools: composer:v2
      - uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --no-interaction --no-progress --ignore-platform-req=php
        if: "matrix.php >= 8"
      - uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --no-interaction --prefer-dist --no-progress
        if: "matrix.php < 8"
      - run: vendor/bin/phpunit --coverage-text
